Remove one of the protobuf cmds

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -269,11 +269,11 @@ install_goprotobuf() {
 			return 1
 		fi
 	else
-		$GVM_GOINSTALL google.golang.org/protobuf/cmd/proto > "$GVM_ROOT/logs/$GO_NAME-pb-compiler.log" 2>&1
-		if [[ $? -ne 0 ]]; then
-			display_warning "Failed to install goprotobuf. Check the logs at $GVM_ROOT/logs/$GO_NAME-pb-compiler.log"
-			return 1
-		fi
+		# $GVM_GOINSTALL google.golang.org/protobuf/cmd/proto > "$GVM_ROOT/logs/$GO_NAME-pb-compiler.log" 2>&1
+		# if [[ $? -ne 0 ]]; then
+		# 	display_warning "Failed to install goprotobuf. Check the logs at $GVM_ROOT/logs/$GO_NAME-pb-compiler.log"
+		# 	return 1
+		# fi
 		$GVM_GOINSTALL google.golang.org/protobuf/cmd/protoc-gen-go > "$GVM_ROOT/logs/$GO_NAME-pb-compiler.log" 2>&1
 		if [[ $? -ne 0 ]]; then
 			display_warning "Failed to install goprotobuf compiler. Check the logs at $GVM_ROOT/logs/$GO_NAME-pb-compiler.log"
